forklift_manager/forklift/urls.py
from django.urls import path
from forklift import views

app_name = 'forklift'
urlpatterns = [
    path('', views.overview, name='overview'),
    
    path('Permission/', views.allow_operator, name='allow_operator'),
]

forklift_manager/forklift_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('forklift.urls')),
]

forklift_manager/forklift/models.py
from django.db import models

# Create your models here.
class Forklift(models.Model):

    serial_no = models.CharField(max_length=30, unique=True)

    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    type = models.CharField(max_length=30)

    max_load = models.IntegerField(default=800)
    hours_run = models.FloatField(default=0)
    next_check = models.DateField(null=True, blank=True, default=None)

    can_operate = models.BooleanField(default=True)
    allowed_operators = models.JSONField(default=list)

    def __str__(self):
        return f'{self.serial_no}'

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Forklift'
        verbose_name_plural = 'Forklifts'

forklift_manager/forklift/views.py
from django.shortcuts import render
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseBase

from forklift.models import Forklift

# Create your views here.
def overview(request: HttpRequest) -> HttpResponseBase:
    return render(request, 'forklift/overview.html', {
        'forklifts': Forklift.objects.all(),
    })


def allow_operator(request: HttpRequest) -> HttpResponseBase:
    try:
        data = request.POST

        forklift = Forklift.objects.get(id=data['forklift_id'])
        operators = set(forklift.allowed_operators)

        if data['allowed'] == 'true':
            operators.add(int(data['operator_id']))
        elif data['operator_id'] in operators:
            operators.remove(int(data['operator_id']))

        forklift.allowed_operators = list(operators)
        forklift.save()
        return HttpResponse()
    except Exception as e:
        return HttpResponseBadRequest(e)

forklift_manager/forklift/templates/forklift/forklift_card.html
<div class="card bg-warning">
    <div class="card-header" style="display: flex; align-items: center; justify-content: space-between;">
        <span>{{ f.serial_no }} ({{ f.brand }})</span>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="can-operate-{{ f.id }}" {% if f.can_operate %}checked{% endif %} onchange="toggle_can_operate({{ f.pk }});">
            <label class="form-check-label" for="can-operate-{{ f.id }}">
                funktionstüchtig
            </label>
        </div>
    </div>
    <div class="card-body">
        <h6>Eingewiesene Fahrer:</h6>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="operator-3-{{ f.id }}" {% if 3 in f.allowed_operators %}checked{% endif %} onchange="toggle_operator(3, {{ f.pk }});">
            <label class="form-check-label" for="operator-3-{{ f.id }}">
                Jan Vetter
            </label>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="operator-8-{{ f.id }}" {% if 8 in f.allowed_operators %}checked{% endif %} onchange="toggle_operator(8, {{ f.pk }});">
            <label class="form-check-label" for="operator-8-{{ f.id }}">
                Dirk Felsenheimer
            </label>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="operator-15-{{ f.id }}" {% if 15 in f.allowed_operators %}checked{% endif %} onchange="toggle_operator(15, {{ f.pk }});">
            <label class="form-check-label" for="operator-15-{{ f.id }}">
                Rodrigo Andrés González Espíndola
            </label>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="operator-17-{{ f.id }}" {% if 17 in f.allowed_operators %}checked{% endif %} onchange="toggle_operator(17, {{ f.pk }});">
            <label class="form-check-label" for="operator-17-{{ f.id }}">
                Alexander Bojcan
            </label>
        </div>

    </div>
    <div class="card-footer p-1">
        <div class="input-group">
            <span class="input-group-text" id="hours-run-{{ f.pk }}">Gelaufene Stunden</span>
            <input type="number" step="0.1" class="form-control" value="{{ f.hours_run }}">
        </div>
    </div>
</div>

forklift_manager/forklift/templates/forklift/overview.html
{% extends 'base.html' %}

{% block title %}Stapler-Übersicht{% endblock title %}

{% block content %}
    <h2>Stapler Übersicht</h2>
    <div style="display: grid; gap: .5rem; grid-template-columns: repeat(5, 1fr);">
        {% for f in forklifts %}
            {% include 'forklift/forklift_card.html' %}
        {% endfor %}
    </div>
{% endblock content %}

{% block script %}
<script>
    function toggle_operator(operator_id, forklift_id) {
        $.post({
            url: '{% url "forklift:allow_operator" %}',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            data: {
                operator_id: operator_id,
                forklift_id: forklift_id,
                allowed: $('#operator-' + operator_id + '-' + forklift_id).prop('checked'),
            },
        }).done(function (data) {
            location.reload();
        }).fail(function (data) {

        }).always(function (data) {

        })
    }

    function toggle_can_operate(forklift_id) {
        // TODO Implement
    }
</script>
{% endblock script %}
    

forklift_manager/forklift_manager/templates/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="p-3">
        {% block content %}
        
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    {% block script %}
        
    {% endblock script %}
</body>
</html>